# Generated by Django 4.2 on 2024-01-15 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Ícono')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('resource_type', models.CharField(choices=[('guide', '📖 Guía'), ('video', '🎥 Video'), ('link', '🔗 Enlace'), ('document', '📄 Documento'), ('presentation', '📊 Presentación'), ('exercise', '💪 Ejercicio'), ('tool', '🛠️ Herramienta')], default='document', max_length=20, verbose_name='Tipo de Recurso')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'zip'])], verbose_name='Archivo')),
                ('url', models.URLField(blank=True, verbose_name='Enlace Externo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/', verbose_name='Miniatura')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Autor')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('views', models.IntegerField(default=0, verbose_name='Visitas')),
                ('downloads', models.IntegerField(default=0, verbose_name='Descargas')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-published_date'],
            },
        ),
    ]
}