# Generated by Django 4.2 on 2025-12-04 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_value',
            field=models.PositiveIntegerField(default=1, verbose_name='Meta (Cantidad)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal')], default='DAILY', max_length=10, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Hábito'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(default='veces', max_length=50, verbose_name='Unidad (ej: páginas, vasos)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HabitRecord',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='color',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='daily_goal',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='habit_type',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
    ]
