# Generated by Django 4.2 on 2026-07-08 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal')], default='DAILY', max_length=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(default='veces', max_length=50),
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField(default=1)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
        ),
    ]
