# Generated by Django 5.2.9 on 2025-12-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Código Estudiantil'),
        ),
    ]
