# Generated by Django 5.2.9 on 2025-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_student_id_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Estudiantil'),
        ),
    ]
