# Generated by Django 4.2 on 2024-01-15 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Hábito')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('habit_type', models.CharField(choices=[('sleep', '💤 Sueño'), ('water', '💧 Agua'), ('exercise', '🏃 Ejercicio'), ('study', '📚 Estudio'), ('meditation', '🧘 Meditación'), ('reading', '📖 Lectura'), ('nutrition', '🍎 Nutrición'), ('productivity', '⏰ Productividad'), ('social', '👥 Social'), ('other', '📌 Otro')], default='other', max_length=20, verbose_name='Tipo de Hábito')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', max_length=10, verbose_name='Frecuencia')),
                ('daily_goal', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Meta Diaria')),
                ('unit', models.CharField(default='veces', max_length=20, verbose_name='Unidad de Medida')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='fas fa-star', max_length=50, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='accounts.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Valor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('mood', models.IntegerField(blank=True, choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')], null=True, verbose_name='Estado de Ánimo')),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Muy Fácil'), (2, 'Fácil'), (3, 'Normal'), (4, 'Difícil'), (5, 'Muy Difícil')], null=True, verbose_name='Dificultad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habits.habit', verbose_name='Hábito')),
            ],
            options={
                'verbose_name': 'Registro de Hábito',
                'verbose_name_plural': 'Registros de Hábitos',
                'ordering': ['-date', 'habit'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
}